name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache
      uses: actions/cache@v1.0.0
    - name: Install
      run: yarn ci
    - name: Test
      run: yarn test-ci
